lcicMain/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse

def home(request):
    return HttpResponse("System is running!")
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('lcicHome.urls', 'lcicHome'), namespace='lcic')),
    path('news/', include(('lcicNews.urls', 'lcicNews'), namespace='news')),
    path('api/', include('lcicHome.urls')),
    path('api/', include('utility.urls')),
    path('', home, name='home'),

    # path('sql/', include('ned_sql.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lcicNews/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('detail/', views.NewDetail, name = 'detail'),
    path('job/', views.jobs, name = 'jobs'),
    path('members/',views.members, name = 'members'),  
    path('products/',views.products, name='products'),
    path('docInfo/',views.documentInfo, name='docInfo')
    
]

utility/urls.py
# urls.py
from django.urls import path
from .views import (STypeListCreate, STypeRetrieveUpdateDestroy, TelecomCusListCreate, TelecomCusRetrieveUpdateDestroy,
                   UploadJsonTelecomView, UploadFileTelecomListCreate, UploadFileTelecomRetrieveUpdateDestroy,TelecomBillListCreate,
                   TelecomBillRetrieveUpdateDestroy,UploadBillJsonFileView)

urlpatterns = [
    path('stype/', STypeListCreate.as_view(), name='stype-list-create'),
    path('stype/<int:pk>/', STypeRetrieveUpdateDestroy.as_view(), name='stype-detail'),
    path('telecom_cus/', TelecomCusListCreate.as_view(), name='telecomcus-list-create'),
    path('telecom_cus/<int:pk>/', TelecomCusRetrieveUpdateDestroy.as_view(), name='telecomcus_detail'),
    path('telecom_bill/', TelecomBillListCreate.as_view(), name='telecombill-list-create'),
    path('telecom_bill/<int:pk>/', TelecomBillRetrieveUpdateDestroy.as_view(), name='telecombill_detail'),
    path('upload-json-telecom/', UploadJsonTelecomView.as_view(), name='upload-json'),
    path('telecom-file/', UploadFileTelecomListCreate.as_view(), name='telecom-file-list-create'),
    path('telecom-file/<int:pk>/', UploadFileTelecomRetrieveUpdateDestroy.as_view(), name='telecom-file-detail'),
    path('upload-bill/', UploadBillJsonFileView.as_view(), name='upload-bill-json'),

]

templates/News/docinfo.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}Document Form{%endblock%}

{% block content %}

<div id="important" class="important">
    <div class="container">
       
      <div class="row">
        <div class="col-md-12">
          <div class="titlepage">
            <h3><strong class="blue">{% if Lang == "la" %}
                {% if Lang == "la" %}
                {% for f in H_form %}
                {{f.Trans_LA}}
              {% endfor %}
              {% elif Lang == "en" %}
              {% for f in H_form %}
                {{f.Trans_EN}}
              {% endfor %}
              {% endif %}
              {% endif %}

              {% if Lang == "en" %}
                {% if Lang == "la" %}
                {% for f in H_form %}
                {{f.Trans_LA}}
              {% endfor %}
              {% elif Lang == "en" %}
              {% for f in H_form %}
                {{f.Trans_EN}}
              {% endfor %}
              {% endif %}
              {% endif %}</strong></h3>
                <div class="container" style="margin-bottom:-100px">
                    <!-- center><figure><img src="{% static 'images/CEO.jpg '%}"></figure></center --> 
                   <hr> 
                   {% if Lang == "la" %}
                   <p>
                      {%for d in documentInfo_v %}                  
                      <a href="{{ d.dFiles.url }}"  target="_blank" > + {{d.nameL}} </a><hr>
                      {%endfor%}
                </p>
                {% endif %}

                {% if Lang == "en" %}
                <p>
                   {%for d in documentInfo_v %}                  
                   <a href="{{ d.dFiles.url }}"  target="_blank" > + {{d.nameE}} </a><hr>
                   {%endfor%}
             </p>
             {% endif %}
                </div>
          </div>
        </div>
      </div>
    </div> <!-- end History -->

{%endblock%}

templates/News/index.html
{% extends 'layouts/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}LCIC News{% endblock %}</title>
</head>

{% block content %}
<div id="important" class="important">
    <div class="container">
      <div class="row">
        
            <div class="col-md-3">
                {% if Lang == "la" %}
                <div class="list-group">
                    <a href="{% url 'lcicNews:index'%}?Lang=la" class="list-group-item list-group-item-action {%if not Type_V %}active{% endif %}" aria-current="true">
                        {% for nl in H_nl %}
                        {{nl.Trans_LA}}
                      {% endfor %}</a>
                    {% for t in newsType_v %}    
                    <a href="{% url 'lcicNews:index' %}?newsTypeid={{ t.id }}&Lang=la" class="list-group-item list-group-item-action {%if Type_V|add:'0' == t.id %}active{% endif %} " aria-current="true">{{t.nameL}}</a>
                    {% endfor %}
                </div>
                 {% elif Lang == "en" %}
                 <div class="list-group">
                    <a href="{% url 'lcicNews:index'%}?Lang=en" class="list-group-item list-group-item-action {%if not Type_V %}active{% endif %}" aria-current="true">
                        {% for nl in H_nl %}
                        {{nl.Trans_EN}}
                      {% endfor %}</a>
                    {% for t in newsType_v %}    
                    <a href="{% url 'lcicNews:index' %}?newsTypeid={{ t.id }}&Lang=en" class="list-group-item list-group-item-action {%if Type_V|add:'0' == t.id %}active{% endif %} " aria-current="true">{{t.nameE}}</a>
                    {% endfor %}
                </div>

                {% endif %}    
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card border-0"> 
                            {% if Lang == "la" %}
                            <div class="row">
                                {% for n in newsInfo_v %}
                                    <div class="col-md-1">                                    
                                        <a href="#"><img src="{{ n.nimage.url }}" class="card-img-top"max-width="100px"></a>
                                    </div>
                                    <div class="col-md-11">
                                        {% if n.nFiles %}
                                        <h6><a href="{{ n.nFiles.url }}">news: {{n.nameL}}</a></h6>     
                                        {% endif %}
                                       <!--<a href="{% url 'lcicNews:detail'%}?slug={{ n.id }}" class="btn btn-info mt-1">ເພີ່ມເຕີມ</a> --> 
                                    </div>
                                {% endfor %}
                            </div>

                            {% elif Lang == "en" %}
                            <div class="row">
                                {% for n in newsInfo_v %}
                                    <div class="col-md-1">                                    
                                        <a href="#"><img src="{{ n.nimage.url }}" class="card-img-top"max-width="100px"></a>
                                    </div>
                                    <div class="col-md-11">
                                        {% if n.nFiles %}
                                        <h6><a href="{{ n.nFiles.url }}">news: {{n.nameE}}</a></h6>     
                                        {% endif %}
                                       <!--<a href="{% url 'lcicNews:detail'%}?slug={{ n.id }}" class="btn btn-info mt-1">ເພີ່ມເຕີມ</a> --> 
                                    </div>
                                {% endfor %}
                            </div>

                            {% endif %}
                        </div>
                    </div>
                </div>
                <hr>
                 <!--<div class="box_text">
                         <a href="{% url 'news:index' %}" class="btn" href="Javascript:void(0)">ອ່ານເພີ່ມເຕີມ</a> 
                    </div> -->
                    {% if Lang == "la" %}
                <ul class="pagination" >                   
                {% if newsInfo_v.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=newsInfo_v.previous_page_number&Lang=la">Previous</a></li>
                {% endif %}
                {% for i in newsInfo_v.paginator.page_range %}
                    <li class="page-item {% if newsInfo_v == i %}active{%endif%}"><a class="page-link" href="?page={{ i }}&Lang=la">{{i}}</a></li>
                {% endfor %}
                {% if newsInfo_v.has_next %}
                    <li class="page-item"><a class="page-link" href="?page=newsInfo_v.next_page_number&Lang=la">Next</a></li>
                {% endif %}
                </ul><!-- end Previour Page and Next Page-->

                {% elif Lang == "en" %}
                <ul class="pagination" >                   
                {% if newsInfo_v.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=newsInfo_v.previous_page_number&Lang=en">Previous</a></li>
                {% endif %}
                {% for i in newsInfo_v.paginator.page_range %}
                    <li class="page-item {% if newsInfo_v == i %}active{%endif%}"><a class="page-link" href="?page={{ i }}&Lang=en">{{i}}</a></li>
                {% endfor %}
                {% if newsInfo_v.has_next %}
                    <li class="page-item"><a class="page-link" href="?page=newsInfo_v.next_page_number&Lang=en">Next</a></li>
                {% endif %}
                </ul><!-- end Previour Page and Next Page-->
                {% endif %}
            </div>
            
        
    </div>
</div> <!-- end History -->
{% endblock %}

</html>

templates/News/jobs.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}job{%endblock%}

{% block content %}
    <div id="important" class="important">
        <div class="container-sm">
            <div class="row mt-2">
                <div class="col-md-12 col-sm-12">
                    <div class="titlepage">
                        {% if Lang == "la" %}
                        <h3>{% for j in H_join %}
                            {{j.Trans_LA}}
                          {% endfor %}<strong class="yellow">
                            {% for com in H_com %}
                            {{com.Trans_LA}}
                          {% endfor %}</strong></h3>

                        {% elif Lang == "en" %}
                        <h3>{% for j in H_join %}
                            {{j.Trans_EN}}
                          {% endfor %}<strong class="yellow">
                            {% for com in H_com %}
                            {{com.Trans_EN}}
                          {% endfor %}</strong></h3>
                        {% endif %}
                            <div class="container" style="margin-bottom:-100px">
                                <figure><img src="{% static 'images/4055.jpeg' %}"></figure> 
                            </div>                           
                    </div>                                     
               
                </div>
                <div class="row mt-5">
                    <div class="col-md-12 col-sm-12">
                    {% if Lang == "la" %}
                     {%for j in jobsInfo_v %}                  
                        <center><a href="{{ j.jfiles.url }}"  target="_blank" > + {{j.nameL}} </a><hr></center>    
                     {%endfor%}</p>

                     {% elif Lang == "en" %}
                     {%for j in jobsInfo_v %}                  
                        <center><a href="{{ j.jfiles.url }}"  target="_blank" > + {{j.nameE}} </a><hr></center>    
                     {%endfor%}</p>
                     {% endif %}
                    </div>
                </div>
            </div>
        </div> <!-- end History -->
    </div>
{%endblock%}

templates/News/members.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}Member Of LCIC{%endblock%}
{% block content %}
<div id="important" class="important">
    <div class="container-sm">
        <div class="row">
            <div class="col-md-3">
                {% if Lang == "la" %}
                <div class="list-group">
                    <a href="{% url 'lcicNews:members'%}?Lang=la" class="list-group-item list-group-item-action {% if not mType_v %}active{%endif%} " aria-current="true">
                       ສະມາຊິກທັງໝົດ</a> 
                    {% for t in memberType_v %}
                    <a href="{% url 'lcicNews:members' %}?memberTypeid={{ t.id }}&Lang=la" class="list-group-item list-group-item-action {%if mType_v|add:'0' == t.id %}active{% endif %} " aria-current="true">{{t.nameL}}</a>
                    {%endfor%}
                </div>

                {% elif Lang == "en" %}
                <div class="list-group">
                    <a href="{% url 'lcicNews:members'%}?Lang=en" class="list-group-item list-group-item-action {% if not mType_v %}active{%endif%} " aria-current="true">{% for all in H_mem %}
                        {{all.Trans_EN}}
                       {% endfor %}</a> 
                    {% for t in memberType_v %}
                    <a href="{% url 'lcicNews:members' %}?memberTypeid={{ t.id }}&Lang=en" class="list-group-item list-group-item-action {%if mType_v|add:'0' == t.id %}active{% endif %} " aria-current="true">{{t.nameE}}</a>
                    {%endfor%}
                </div>
                {% endif %}
            </div>
            <div class="col-md-9">
                <div class="row ">
                    <div class="col-md-12">
                        <div class="card border-0">
                            {% if Lang == "la" %}
                            <div class="row">
                                {% for m in memberInfo_v %}
                                    <div class="col-md-1">
                                    {% if m.mImage %} 
                                        <a href="#"><img src="{{ m.mImage.url }}" alt="" class="card-img-top"max-width="50px"></a>
                                    {%endif%} 
                                    </div>
                                    <div class="col-md-11">
                                        <h6><strong class="blue">{{m.nameL}}</strong></h6>
                                        <span>ທີ່ຢູ່: {{m.streetInfoL}} {{m.villageInfo}} {{m.districtInfo}} {{m.provInfo}} </span>
                                    </div>
                                {%endfor%}
                            </div>

                            {% elif Lang == "en" %}
                            <div class="row">
                                {% for m in memberInfo_v %}
                                    <div class="col-md-1">
                                    {% if m.mImage %} 
                                        <a href="#"><img src="{{ m.mImage.url }}" alt="" class="card-img-top"max-width="50px"></a>
                                    {%endif%} 
                                    </div>
                                    <div class="col-md-11">
                                        <h6><strong class="blue">{{m.nameE}}</strong></h6>
                                        <span>Address: {{m.streetInfoE}} {{m.villageInfo.nameE}} {{m.districtInfo.nameE}} {{m.provInfo.nameE}} </span>
                                    </div>
                                {%endfor%}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <hr>
                {% if Lang == "la" %}
                    <ul class="pagination" >                   
                        {% if memberInfo_v.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=memberInfo_v.previous_page_number&Lang=la">Previous</a></li>
                        {% endif %}
                        {% for i in memberInfo_v.paginator.page_range %}
                            <li class="page-item {% if memberInfo_v == i %}active{%endif%}"><a class="page-link" href="?page={{ i }}&Lang=la">{{i}}</a></li>
                        {% endfor %}
                        {% if memberInfo_v.has_next %}
                            <li class="page-item"><a class="page-link" href="?page=memberInfo_v.next_page_number&Lang=la">Next</a></li>
                        {% endif %}
                    </ul><!-- end Previour Page and Next Page-->

                    {% elif Lang == "en" %}
                    <ul class="pagination" >                   
                        {% if memberInfo_v.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=memberInfo_v.previous_page_number&Lang=en">Previous</a></li>
                        {% endif %}
                        {% for i in memberInfo_v.paginator.page_range %}
                            <li class="page-item {% if memberInfo_v == i %}active{%endif%}"><a class="page-link" href="?page={{ i }}&Lang=en">{{i}}</a></li>
                        {% endfor %}
                        {% if memberInfo_v.has_next %}
                            <li class="page-item"><a class="page-link" href="?page=memberInfo_v.next_page_number&Lang=en">Next</a></li>
                        {% endif %}
                    </ul><!-- end Previour Page and Next Page-->
                    {% endif %}
            </div>
            
        </div>
    </div> <!-- end History -->
</div>
{%endblock%}

templates/News/newsDetail.html
{% extends 'layouts/base.html' %}
{% block title %}News Detail{%endblock%}

{% block content %}

{%endblock%}

templates/News/products.html
{% extends "layouts/base.html" %}
{% block title %}Products{%endblock%}

{% block content %}
<div id=important class="important">
  <div class="container-sm">
    <div class="row">
      <div class="col-sm-3">
        {% if Lang == "la" %}
        <div class="list-group">
          <!-- a href="{% url 'lcicNews:products'%}" class="list-group-item list-group-item-action {% if not pType_v %}active{%endif%} " aria-current="true">ຜະລິດຕະພັນ&ການບໍລິການທັງໝົດ</a--> 
          {% for t in proType_v %}
          <a href="{% url 'lcicNews:products' %}?proTypeid={{ t.id }}&Lang=la" class="list-group-item list-group-item-action {%if pType_v|add:'0' == t.id %}active{%endif%}  " aria-current="true">{{t.nameL}}</a>
          {%endfor%}
      </div>

      {% elif Lang == "en" %}
        <div class="list-group">
          <!-- a href="{% url 'lcicNews:products'%}" class="list-group-item list-group-item-action {% if not pType_v %}active{%endif%} " aria-current="true">ຜະລິດຕະພັນ&ການບໍລິການທັງໝົດ</a--> 
          {% for t in proType_v %}
          <a href="{% url 'lcicNews:products' %}?proTypeid={{ t.id }}&Lang=en" class="list-group-item list-group-item-action {%if pType_v|add:'0' == t.id %}active{%endif%}  " aria-current="true">{{t.nameE}}</a>
          {%endfor%}
      </div>
      {% endif %}
      </div> <!-- end menu type of Product( proType )-->
      <div class="col-sm-9">
        <div class="row">
          <div class="col-sm-12">
            {% if Lang == "la" %}
            <div class="card border-0">
              {%for p in productInfo_v %}
                <div class="row">
                  <div class="col-sm-3">                    
                    {% if p.pimage %} 
                    <a href="{{ p.pFiles.url }}"><img src="{{ p.pimage.url }}" alt="" class="card-img-top mt-2"max-width="50px"></a>
                    {%endif%} 
                  </div>
                  <div class="col-sm-9">   
                    {% if p.pFiles %}                 
                    <a href="{{ p.pFiles.url }}"><h3><strong class="blue">{{p.nameL}} </strong></h3></a>
                    {% endif %}
                    <span class="text-align:left!important">{{ p.descL }}</span>                        
                  </div>
                </div> 
              {%endfor%}             
            </div>

            {% elif Lang == "en" %}
            <div class="card border-0">
              {%for p in productInfo_v %}
                <div class="row">
                  <div class="col-sm-3">                    
                    {% if p.pimage %} 
                    <a href="{{ p.pFiles.url }}"><img src="{{ p.pimage.url }}" alt="" class="card-img-top mt-2"max-width="50px"></a>
                    {%endif%} 
                  </div>
                  <div class="col-sm-9">   
                    {% if p.pFiles %}                 
                    <a href="{{ p.pFiles.url }}"><h3><strong class="blue">{{p.nameE}} </strong></h3></a>
                    {% endif %}
                    <span class="text-align:left!important">{{ p.descE }}</span>                        
                  </div>
                </div> 
              {%endfor%}             
            </div>
            {% endif %}
          </div>
        </div>
      </div><!-- end image box-->
    </div><!-- end Main image box-->
  </div>
</div>

{%endblock%}